import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import Header from "@/components/header/Header";
import AdvancedCursor from "@/components/shared/AdvancedCursor";
import BodyParallax from "@/components/shared/BodyParalax";
import { iranYekan } from "./(main)/Style/fonts";
import Footer from "@/components/footer/Footer";
import Whatsupp from "@/components/shared/Whatsupp";
import PageTransitionWrapper from "@/components/PageTranistionWrapper";
const poppins = Poppins({
  variable: "--font-poppins",
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Apex Smart Marketing",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en' dir='rtl'>
      <body className={`${iranYekan.variable} antialiased`}>
        <div
          className='fixed inset-0 bg-center bg-cover z-[-1]'
          style={{ backgroundImage: 'url("/assets/hero.jpg")' }}></div>
        <Header />
        <AdvancedCursor />
        <BodyParallax />
        {children}
        <Whatsupp />
        <Footer />
      </body>
    </html>
  );
}
